---
title: "DGMD S-14 Notebook"
subtitle: Spring 2021
output: 
pdf_document: default
  html_document:
    df_print: paged
---



Let's clear the global computing environment:
```{r}
rm( list = ls() )
```


Load csv files
```{r}

first.pedaling.set <- read.csv("./7262021/07262021 data - 07262021_1.csv")
#trial.perfect.set <- read.csv("./7262021/07262021 data - trial_perfect.csv")
toes.data.set <- read.csv("./7262021/07282021_trial_toes.csv")
```


organize data by sensor (acc, gyr, mag)



```{r}
first.pedaling.set$timestamp <- paste(first.pedaling.set$X.1, first.pedaling.set$X, sep="")
first.pedaling.set$acc_x <- paste(first.pedaling.set$X.3, first.pedaling.set$X.2, sep="")
first.pedaling.set$acc_y <- paste(first.pedaling.set$X.5, first.pedaling.set$X.4, sep="")
first.pedaling.set$acc_z <- paste(first.pedaling.set$X.7, first.pedaling.set$X.6, sep="")
first.pedaling.set$gyr_x <- paste(first.pedaling.set$X.9, first.pedaling.set$X.8, sep="")
first.pedaling.set$gyr_y <- paste(first.pedaling.set$X.11, first.pedaling.set$X.10, sep="")
first.pedaling.set$gyr_z <- paste(first.pedaling.set$X.13, first.pedaling.set$X.12, sep="")
first.pedaling.set$mag_x <- paste(first.pedaling.set$X.15, first.pedaling.set$X.14, sep="")
first.pedaling.set$mag_y <- paste(first.pedaling.set$X.17, first.pedaling.set$X.16, sep="")
first.pedaling.set$mag_z <- paste(first.pedaling.set$X.19, first.pedaling.set$X.18, sep="")

toes.data.set$timestamp <- paste(toes.data.set$X.1, toes.data.set$X, sep="")
toes.data.set$acc_x <- paste(toes.data.set$X.3, toes.data.set$X.2, sep="")
toes.data.set$acc_y <- paste(toes.data.set$X.5, toes.data.set$X.4, sep="")
toes.data.set$acc_z <- paste(toes.data.set$X.7, toes.data.set$X.6, sep="")
toes.data.set$gyr_x <- paste(toes.data.set$X.9, toes.data.set$X.8, sep="")
toes.data.set$gyr_y <- paste(toes.data.set$X.11, toes.data.set$X.10, sep="")
toes.data.set$gyr_z <- paste(toes.data.set$X.13, toes.data.set$X.12, sep="")
toes.data.set$mag_x <- paste(toes.data.set$X.15, toes.data.set$X.14, sep="")
toes.data.set$mag_y <- paste(toes.data.set$X.17, toes.data.set$X.16, sep="")
toes.data.set$mag_z <- paste(toes.data.set$X.19, toes.data.set$X.18, sep="")


```

Convert hex to dec values
```{r}

hextodec <- function(df){
decimal.data.frame <- data.frame(
  
timestamp.dec = strtoi(df$timestamp, base = 16),
acc_x_dec = strtoi(df$acc_x, base = 16),
acc_y_dec = strtoi(df$acc_y, base = 16),
acc_z_dec = strtoi(df$acc_z, base = 16),
gyr_x_dec = strtoi(df$gyr_x, base = 16),
gyr_y_dec = strtoi(df$gyr_y, base = 16),
gyr_z_dec = strtoi(df$gyr_z, base = 16),
mag_x_dec = strtoi(df$mag_x, base = 16),
mag_y_dec = strtoi(df$mag_y, base = 16),
mag_z_dec = strtoi(df$mag_z, base = 16)
)
return (decimal.data.frame)

}

first.pedaling.set <- hextodec(first.pedaling.set)
toes.data.set <- hextodec(toes.data.set)
```


```{r}
#first.pedaling.set$timestamp_dec <- strtoi(first.pedaling.set$timestamp, base = 16)
#first.pedaling.set$acc_x_dec <- strtoi(first.pedaling.set$acc_x, base = 16)
#first.pedaling.set$acc_y_dec <- strtoi(first.pedaling.set$acc_y, base = 16)
#first.pedaling.set$acc_z_dec <- strtoi(first.pedaling.set$acc_z, base = 16)
#first.pedaling.set$gyr_x_dec <- strtoi(first.pedaling.set$gyr_x, base = 16)
#first.pedaling.set$gyr_y_dec <- strtoi(first.pedaling.set$gyr_y, base = 16)
#first.pedaling.set$gyr_z_dec <- strtoi(first.pedaling.set$gyr_z, base = 16)
#first.pedaling.set$mag_x_dec <- strtoi(first.pedaling.set$mag_x, base = 16)
#first.pedaling.set$mag_y_dec <- strtoi(first.pedaling.set$mag_y, base = 16)
#first.pedaling.set$mag_z_dec <- strtoi(first.pedaling.set$mag_z, base = 16)
```



```{r}
for (index in 1:length(first.pedaling.set$acc_x_dec)){
    if(first.pedaling.set$acc_x_dec[index] > 32767){
        first.pedaling.set$acc_x_dec[index] <- first.pedaling.set$acc_x_dec[index] - 65536
    }
}

for (index in 1:length(first.pedaling.set$acc_y_dec)){
    if(first.pedaling.set$acc_y_dec[index] > 32767){
        first.pedaling.set$acc_y_dec[index] <- first.pedaling.set$acc_y_dec[index] - 65536
    }
}
    
for (index in 1:length(first.pedaling.set$acc_z_dec)){
    if(first.pedaling.set$acc_z_dec[index] > 32767){
        first.pedaling.set$acc_z_dec[index] <- first.pedaling.set$acc_z_dec[index] - 65536
    }
    first.pedaling.set$acc_z_dec[index] <- first.pedaling.set$acc_z_dec[index] - 1000
}
    
for (index in 1:length(first.pedaling.set$gyr_x_dec)){
    if(first.pedaling.set$gyr_x_dec[index] > 32767){
        first.pedaling.set$gyr_x_dec[index] <- first.pedaling.set$gyr_x_dec[index] - 65536
    } 
}

for (index in 1:length(first.pedaling.set$gyr_y_dec)){
    if(first.pedaling.set$gyr_y_dec[index] > 32767){
        first.pedaling.set$gyr_y_dec[index] <- first.pedaling.set$gyr_y_dec[index] - 65536
    } 
}
for (index in 1:length(first.pedaling.set$gyr_z_dec)){
    if(first.pedaling.set$gyr_z_dec[index] > 32767){
        first.pedaling.set$gyr_z_dec[index] <- first.pedaling.set$gyr_z_dec[index] - 65536
    } 
}

for (index in 1:length(first.pedaling.set$mag_x_dec)){
    if(first.pedaling.set$mag_x_dec[index] > 32767){
        first.pedaling.set$mag_x_dec[index] <- first.pedaling.set$mag_x_dec[index] - 65536
    } 
}

for (index in 1:length(first.pedaling.set$mag_y_dec)){
    if(first.pedaling.set$mag_y_dec[index] > 32767){
        first.pedaling.set$mag_y_dec[index] <- first.pedaling.set$mag_y_dec[index] - 65536
    } 
}
for (index in 1:length(first.pedaling.set$mag_z_dec)){
    if(first.pedaling.set$mag_z_dec[index] > 32767){
        first.pedaling.set$mag_z_dec[index] <- first.pedaling.set$mag_z_dec[index] - 65536
    } 
}
```


```{r}
for (index in 1:length(toes.data.set$acc_x_dec)){
    if(toes.data.set$acc_x_dec[index] > 32767){
        toes.data.set$acc_x_dec[index] <- toes.data.set$acc_x_dec[index] - 65536
    }
}

for (index in 1:length(toes.data.set$acc_y_dec)){
    if(toes.data.set$acc_y_dec[index] > 32767){
        toes.data.set$acc_y_dec[index] <- toes.data.set$acc_y_dec[index] - 65536
    }
}
    
for (index in 1:length(toes.data.set$acc_z_dec)){
    if(toes.data.set$acc_z_dec[index] > 32767){
        toes.data.set$acc_z_dec[index] <- toes.data.set$acc_z_dec[index] - 65536
    }
    toes.data.set$acc_z_dec[index] <- toes.data.set$acc_z_dec[index] - 1000
}
    
for (index in 1:length(toes.data.set$gyr_x_dec)){
    if(toes.data.set$gyr_x_dec[index] > 32767){
        toes.data.set$gyr_x_dec[index] <- toes.data.set$gyr_x_dec[index] - 65536
    } 
}

for (index in 1:length(toes.data.set$gyr_y_dec)){
    if(toes.data.set$gyr_y_dec[index] > 32767){
        toes.data.set$gyr_y_dec[index] <- toes.data.set$gyr_y_dec[index] - 65536
    } 
}
for (index in 1:length(toes.data.set$gyr_z_dec)){
    if(toes.data.set$gyr_z_dec[index] > 32767){
        toes.data.set$gyr_z_dec[index] <- toes.data.set$gyr_z_dec[index] - 65536
    } 
}

for (index in 1:length(toes.data.set$mag_x_dec)){
    if(toes.data.set$mag_x_dec[index] > 32767){
        toes.data.set$mag_x_dec[index] <- toes.data.set$mag_x_dec[index] - 65536
    } 
}

for (index in 1:length(toes.data.set$mag_y_dec)){
    if(toes.data.set$mag_y_dec[index] > 32767){
        toes.data.set$mag_y_dec[index] <- toes.data.set$mag_y_dec[index] - 65536
    } 
}
for (index in 1:length(toes.data.set$mag_z_dec)){
    if(toes.data.set$mag_z_dec[index] > 32767){
        toes.data.set$mag_z_dec[index] <- toes.data.set$mag_z_dec[index] - 65536
    } 
}

for (index in 918:length(toes.data.set$timestamp.dec)){
        
  if(index < 918){
    toes.data.set$timestamp.dec[index] <- toes.data.set$timestamp.dec[index]
  }
  
  else if (index >= 918){toes.data.set$timestamp.dec[index] <- toes.data.set$timestamp.dec[index] + 65536
    } 
}

```


```{r}
plot(
    x = NULL,
    xlim = c(37000, 45000),
    ylim = c(min(first.pedaling.set$acc_x_dec), max(first.pedaling.set$acc_x_dec))
)

lines (
    x = first.pedaling.set$timestamp.dec,
    y = first.pedaling.set$acc_x_dec
    
)
```

```{r}
plot(
    x = NULL,
    xlim = c(37000, 52000),
    ylim = c(min(first.pedaling.set$acc_z_dec), max(first.pedaling.set$acc_z_dec))
)

lines (
    x = first.pedaling.set$timestamp.dec,
    y = first.pedaling.set$acc_z_dec
    
)

```

```{r}
plot(
    x = NULL,
    xlim = c(64000, 71000),
    ylim = c(-1500, 1500),
    main = "Toe Down ACC_Z Dataset before cleaning",
    xlab = "Timestamp",
    ylab = "Force (milli-g)",
    
)

lines (
    x = toes.data.set$timestamp.dec,
    y = toes.data.set$acc_z_dec,
    col = "red"
    
)
```




```{r}
plot(
    x = NULL,
    xlim = c(37000, 45000),
    ylim = c(min(first.pedaling.set$acc_y_dec), max(first.pedaling.set$acc_y_dec))
)

lines (
    x = first.pedaling.set$timestamp.dec,
    y = first.pedaling.set$acc_y_dec
    
)
```
```{r}
plot(
    x = NULL,
    xlim = c(37000, 45000),
    ylim = c(min(first.pedaling.set$gyr_x_dec), max(first.pedaling.set$gyr_x_dec))
)

lines (
    x = first.pedaling.set$timestamp.dec,
    y = first.pedaling.set$gyr_x_dec
    
)

```
```{r}

plot(
    x = NULL,
    xlim = c(37000, 45000),
    ylim = c(min(first.pedaling.set$gyr_y_dec), max(first.pedaling.set$gyr_y_dec))
)

lines (
    x = first.pedaling.set$timestamp.dec,
    y = first.pedaling.set$gyr_y_dec
    
)

```
```{r}
plot(
    x = NULL,
    xlim = c(37000, 45000),
    ylim = c(min(first.pedaling.set$gyr_z_dec), max(first.pedaling.set$gyr_z_dec))
)

lines (
    x = first.pedaling.set$timestamp.dec,
    y = first.pedaling.set$gyr_z_dec
    
)
```
```{r}

plot(
    x = NULL,
    xlim = c(37000, 45000),
    ylim = c(min(first.pedaling.set$mag_x_dec), max(first.pedaling.set$mag_x_dec))
)

lines (
    x = first.pedaling.set$timestamp.dec,
    y = first.pedaling.set$mag_x_dec
    
)
```
```{r}
plot(
    x = NULL,
    xlim = c(37000, 45000),
    ylim = c(min(first.pedaling.set$mag_y_dec), max(first.pedaling.set$mag_y_dec))
)

lines (
    x = first.pedaling.set$timestamp.dec,
    y = first.pedaling.set$mag_y_dec
    
)
```
```{r}
plot(
    x = NULL,
    xlim = c(37000, 45000),
    ylim = c(min(first.pedaling.set$mag_z_dec), max(first.pedaling.set$mag_z_dec))
)

lines (
    x = first.pedaling.set$timestamp.dec,
    y = first.pedaling.set$mag_z_dec
    
)

```
```{r}

plot(
    x = NULL,
    xlim = c(37000, 45000),
    ylim = c(-1500, 1500)
)

lines (
    x = first.pedaling.set$timestamp.dec,
    y = first.pedaling.set$acc_z_dec,
    col = "blue"
)

lines (
    x = first.pedaling.set$timestamp.dec,
    y = first.pedaling.set$acc_y_dec,
    col = "red"
)


```
```{r}

plot(
    x = NULL,
    xlim = c(37000, 45000),
    ylim = c(-1800, 1800)
)
lines (
    x = first.pedaling.set$timestamp.dec,
    y = first.pedaling.set$gyr_x_dec,
    col = "red"
    
)
lines (
    x = first.pedaling.set$timestamp.dec,
    y = first.pedaling.set$gyr_z_dec
    
)

```
```{r}

plot(
    x = NULL,
    xlim = c(37000, 52000),
    ylim = c(-1500, 1500)
)
lines (
    x = first.pedaling.set$timestamp.dec,
    y = first.pedaling.set$mag_x_dec,
    col = "red"
    
)
lines (
    x = first.pedaling.set$timestamp.dec,
    y = first.pedaling.set$mag_y_dec
    
)

lines (
    x = first.pedaling.set$timestamp.dec,
    y = first.pedaling.set$mag_z_dec,
    col = "blue"
)

```

This moving average function was created when I took the R class. It takes the moving average over 3 points
```{r}

moving.average.function <- function(input.vector){
  smoothed.vector.data <- 0
  smoothed.vector.data[1] <- input.vector[1]
  
  for(index in 2:length(input.vector-1)){
  smoothed.vector.data[index] <- 
    (input.vector[index-1] + input.vector[index] + input.vector[index+1])/3
  }
  smoothed.vector.data[length(input.vector)] <- input.vector[length(input.vector)]
  return(smoothed.vector.data)
}

acc_z_smoothed <- moving.average.function(first.pedaling.set$acc_z_dec)
```

```{r}
plot(
    x = NULL,
    xlim = c(38000, 42000),
    ylim = c(-1500, 1500),
    main = "Acceleration Z axis for one set",
    xlab = "timestamp (ms)",
    ylab = "acceleration (milli-g)"
)
lines (
    x = first.pedaling.set$timestamp.dec,
    y = first.pedaling.set$acc_z_dec,
    col = "black",
    lwd = 1
    
)
lines (
    x = first.pedaling.set$timestamp.dec,
    y = acc_z_smoothed,
    lwd = 2,
    col = "red"
    
)

legend(
  x = 37900,
  y = 1550,
  col = c("black", "red"),
  lwd = 1,
  legend = c("Raw data", "Smoothed")
)

```



```{r}
acc_y_smoothed <- moving.average.function(first.pedaling.set$acc_y_dec)

plot(
    x = NULL,
    xlim = c(38000, 42000),
    ylim = c(-1500, 1500)
)
lines (
    x = first.pedaling.set$timestamp.dec,
    y = first.pedaling.set$acc_y_dec,
    col = "red"
    
)
lines (
    x = first.pedaling.set$timestamp.dec,
    y = acc_y_smoothed
    
)


```

```{r}
acc_x_smoothed <- moving.average.function(first.pedaling.set$acc_x_dec)

plot(
    x = NULL,
    xlim = c(38000, 42000),
    ylim = c(-1500, 1500)
)
lines (
    x = first.pedaling.set$timestamp.dec,
    y = first.pedaling.set$acc_x_dec,
    col = "red"
    
)
lines (
    x = first.pedaling.set$timestamp.dec,
    y = acc_x_smoothed
    
)
```
```{r}
gyr_x_smoothed <- moving.average.function(first.pedaling.set$gyr_x_dec)

plot(
    x = NULL,
    xlim = c(38000, 42000),
    ylim = c(-1500, 1500)
)
lines (
    x = first.pedaling.set$timestamp.dec,
    y = first.pedaling.set$gyr_x_dec,
    col = "red"
    
)
lines (
    x = first.pedaling.set$timestamp.dec,
    y = gyr_x_smoothed
    
)
```

```{r}

gyr_y_smoothed <- moving.average.function(first.pedaling.set$gyr_y_dec)

plot(
    x = NULL,
    xlim = c(38000, 42000),
    ylim = c(-1500, 1500)
)
lines (
    x = first.pedaling.set$timestamp.dec,
    y = first.pedaling.set$gyr_y_dec,
    col = "red"
    
)
lines (
    x = first.pedaling.set$timestamp.dec,
    y = gyr_y_smoothed
    
)

```

```{r}

gyr_z_smoothed <- moving.average.function(first.pedaling.set$gyr_z_dec)

plot(
    x = NULL,
    xlim = c(38000, 42000),
    ylim = c(-1500, 1500)
)
lines (
    x = first.pedaling.set$timestamp.dec,
    y = first.pedaling.set$gyr_z_dec,
    col = "red"
    
)
lines (
    x = first.pedaling.set$timestamp.dec,
    y = gyr_z_smoothed
    
)
```
```{r}

mag_x_smoothed <- moving.average.function(first.pedaling.set$mag_x_dec)

plot(
    x = NULL,
    xlim = c(38000, 42000),
    ylim = c(-1500, 1500)
)
lines (
    x = first.pedaling.set$timestamp.dec,
    y = first.pedaling.set$mag_x_dec,
    col = "red"
    
)
lines (
    x = first.pedaling.set$timestamp.dec,
    y = mag_x_smoothed
    
)

```

```{r}
mag_y_smoothed <- moving.average.function(first.pedaling.set$mag_y_dec)

plot(
    x = NULL,
    xlim = c(38000, 42000),
    ylim = c(-1500, 1500)
)
lines (
    x = first.pedaling.set$timestamp.dec,
    y = first.pedaling.set$mag_y_dec,
    col = "red"
    
)
lines (
    x = first.pedaling.set$timestamp.dec,
    y = mag_y_smoothed
    
)

```
```{r}

mag_z_smoothed <- moving.average.function(first.pedaling.set$mag_z_dec)

plot(
    x = NULL,
    xlim = c(38000, 42000),
    ylim = c(-1500, 1500)
)
lines (
    x = first.pedaling.set$timestamp.dec,
    y = first.pedaling.set$mag_z_dec,
    col = "red"
    
)
lines (
    x = first.pedaling.set$timestamp.dec,
    y = mag_z_smoothed
    
)
```
```{r}

smoothed.data.first <- data.frame(first.pedaling.set$timestamp.dec, acc_x_smoothed, acc_y_smoothed, acc_z_smoothed, gyr_x_smoothed, gyr_y_smoothed, gyr_z_smoothed, mag_x_smoothed, mag_y_smoothed, mag_z_smoothed)

smoothed.toes.data <- data.frame(
  timestamp.dec = toes.data.set$timestamp.dec,
  acc_x_smoothed = moving.average.function(toes.data.set$acc_x_dec),
  acc_y_smoothed = moving.average.function(toes.data.set$acc_y_dec),
  acc_z_smoothed = moving.average.function(toes.data.set$acc_z_dec),
  gyr_x_smoothed = moving.average.function(toes.data.set$gyr_x_dec),
  gyr_y_smoothed = moving.average.function(toes.data.set$gyr_y_dec),
  gyr_z_smoothed = moving.average.function(toes.data.set$gyr_z_dec),
  mag_x_smoothed = moving.average.function(toes.data.set$mag_x_dec),
  mag_y_smoothed = moving.average.function(toes.data.set$mag_y_dec),
  mag_z_smoothed = moving.average.function(toes.data.set$mag_z_dec)
)



```


Data cleaning
```{r}

cleaned.data.first <- smoothed.data.first[c(1452:1846, 1848:1931, 1934:2340, 2342:3290, 3294:nrow(smoothed.data.first)),]

cleaned.data.toes <- smoothed.toes.data[c(757:874, 912:917, 919:982, 984:1041, 1047:1079, 1081, 1083:1215, 1217:1353, 1357:nrow(smoothed.toes.data)),]

```


```{r}
plot(
    x = NULL,
    xlim = c(64750, 70500),
    ylim = c(-1500, 1500)
)

lines (
    x = cleaned.data.toes$timestamp.dec,
    y = cleaned.data.toes$acc_z_smoothed
    
)
```
```{r}
plot(
    x = NULL,
    xlim = c(64000, 70500),
    ylim = c(-1500, 1500),
    main = "Toe Down ACC_Z Dataset before and after smoothing/cleaning",
    xlab = "Timestamp (ms)",
    ylab = "Force (milli-g)",
    
)

lines (
    x = toes.data.set$timestamp.dec,
    y = toes.data.set$acc_z_dec,
    col = "black"
    
)

lines (
    x = cleaned.data.toes$timestamp.dec,
    y = cleaned.data.toes$acc_z_smoothed,
    col = "red",
    lwd = 2
)

legend(
  x = 64000,
  y = 1550,
  col = c("black", "red"),
  lwd = 1,
  legend = c("Raw data", "Smoothed")
)
```



```{r}

divide.data.function <- function(df, filename){
  state <- 0
  count <- 0
  current.timestamp <- c(0)
  timestamp.zero <- df[1,1]
  index <- 0
  loop.count <- 0

  for( index in 1:nrow(df)){
  
    current.timestamp[index] <- count*6
    
    if ((state == 0) && (df[index, 4] < 0)){
      state <- 0
      count <- count + 1
      index <- index + 1
    }
    
    else if((state == 0) && (df[index, 4] >= 0)){
      state <- 1
      count <- count + 1
      index <- index + 1
    }
    
    else if((state == 1) && (df[index, 4] >= 0)){
      state <- 1
      count <- count + 1
      index <- index + 1
    }
    
    else if ((state == 1) && (df[index, 4] < 0)){
      state <- 0
      
      output.data.frame <- data.frame(
        timestamp = current.timestamp[c((index-count):index)],
        acc_x = df$acc_x_smoothed[c((index-count):index)],
        acc_y = df$acc_y_smoothed[c((index-count):index)],
        acc_z = df$acc_z_smoothed[c((index-count):index)],
        gyr_x = df$gyr_x_smoothed[c((index-count):index)],
        gyr_x = df$gyr_y_smoothed[c((index-count):index)],
        gyr_x = df$gyr_z_smoothed[c((index-count):index)],
        mag_x = df$mag_x_smoothed[c((index-count):index)],
        mag_y = df$mag_y_smoothed[c((index-count):index)],
        mag_z = df$mag_z_smoothed[c((index-count):index)]
      )
      
      loop.count <- loop.count+1
      write.csv(output.data.frame, file = paste(filename, loop.count, ".csv"), row.names = FALSE)
        
      index <- index + 1
      count <- 0
      
    }
}
  
  
  }

divide.data.function(cleaned.data.toes, "toes_data_6ms")
divide.data.function(cleaned.data.first, "first_data_6ms")

```



```{r}
#write.csv(smoothed.data.first, file = "smoothed_trial_data.csv")
```

```{r}

good.stroke.example <- read.csv("./7262021/data standard freq/first_data_6ms 33 .csv" )
flat.stroke.example <- read.csv("./7262021/data standard freq/first_data_6ms 3 .csv" )
toes.stroke.example <- read.csv("./7262021/data standard freq/toes_data_6ms 9 .csv" )

```

```{r}
plot(
    x = NULL,
    xlim = c(0,110),
    ylim = c(-1500, 1500),
    main = "Example ACC Z data for a single stroke",
    xlab = "time (ms)",
    ylab = "force (milli-g)"
)

lines (
    x = good.stroke.example$timestamp,
    y = good.stroke.example$acc_z,
    col = "blue"
)
```

```{r}
plot(
    x = NULL,
    xlim = c(0,120),
    ylim = c(-1500, 1500),
    main = "Example ACC Z data for different strokes",
    xlab = "time (ms)",
    ylab = "force (milli-g)"
)

lines (
    x = good.stroke.example$timestamp,
    y = good.stroke.example$acc_z,
    col = "blue"
)

lines (
    x =flat.stroke.example$timestamp,
    y = flat.stroke.example$acc_z,
    col = "orange"
)

lines (
    x = toes.stroke.example$timestamp,
    y = toes.stroke.example$acc_z,
    col = "red"
)

legend(
  x = 0,
  y = 1400,
  col = c("blue", "orange", "red"),
  lwd = 1,
  legend = c("Good", "Flat", "Toes Down")
)

```

